### ISSUE TITLE
Included tensorflow incompatible with older mac editions? 

### ISSUE THREAD

**Issue by MeijisIrlnd** [gvne/spleeterpp#16]
oh god its me again, hope you're doing well and keeping safe etc!
So my hdd corrupted yesterday, meaning I had to rebuild ALL my libraries I was using in my project, just going to include spleeterpp, but at runtime it gave me: `DYLD: Symbol not found: ____chkstk_darwin`, I'm on OSX 10.13 (high sierra), but I didn't have this issue last time, I think because I built it before the tensorflow binary got included with the rest of the code!
Is my best course of action here to rebuild the tensorflow_cc binary, or is it something else I'm missing?

**Comment by gvne** [comment]
Hi @MeijisIrlnd and sorry for your loss !
It must indeed be a problem with the built tensorflow.

What I can suggest is instead on relying on `tensorflow_cc`, try the develop branch with the `spleeter_enable_filter` option to OFF when generating the solution:
```
cmake -GXcode -Dspleeter_enable_filter=OFF ..
```

The thing is that the develop branch no longer relies on the `tensorflow_cc` library but instead uses the tensorflow C API. The cmake scripts will download it for you [here](https://www.tensorflow.org/install/lang_c)
This hasn't been released yet because it lacks of documentation but it should work just as before . 

Hope this helps !

**Comment by MeijisIrlnd** [comment]
Ughhh I'm struggling on building this, would you be able to give me a step by step? I've done git clone, git checkout origin/develop and git pull origin develop, then mkdir build && cd build, but when I run the cmake command above, I get 
![Screen Shot 2020-04-24 at 16 27 21](https://user-images.githubusercontent.com/38221014/80229673-af989080-8648-11ea-9f05-aa19d224c540.png)

**Comment by gvne** [comment]
I've never experienced an error like that before.
Are you able to build dummy a C++ source file with Xcode ? It looks like there are no C++ complier available on your system.

**Comment by MeijisIrlnd** [comment]
Yeah I am, and gcc and g++ are on the path, super weird right?

**Comment by gvne** [comment]
The -GXcode forces to use Xcode to compile the projet. My guess is that CMake can't find it. If you don't use it for your project using gcc is perfecly fine

**Comment by MeijisIrlnd** [comment]
Yeah so it all built ok, tensorflow included! Thanks so much for your help, I mean classic me I'm struggling to include spleeter with Juce but I'm sure I'll get there, stay safe dude!

**Comment by gvne** [comment]
If you want to check a juce integration you can check [this](https://github.com/gvne/vstSpleeter) or even [this](https://github.com/gvne/urSpleeter) out.  
For the plugin version, build instruction were discussed in an [issue](https://github.com/gvne/vstSpleeter/issues/1). Hope that helps !

Don't hesitate to close the issue when you're done

**Comment by MeijisIrlnd** [comment]
OO having a look at these unreal thank you!! I'm getting `dyld: Library not loaded: @rpath/libtensorflow.1.dylib
  Referenced from: /Users/sylmorrison/Documents/Dev/TestTensorflow/Builds/MacOSX/build/Debug/TestTensorflow.app/Contents/MacOS/TestTensorflow
  Reason: image not found` at runtime, but it LOOKS like the post build shell script might do something in the vein of fixing that?

**Comment by MeijisIrlnd** [comment]
You are an actual saint, it builds and runs, thank you so so much!

**Comment by gvne** [comment]
You are very welcome ! Have fun :)

**Comment by peanutismint** [comment]
Hey guys, apologies for hijacking this thread but I'm experiencing similar problems compiling with gcc (even though it shows as installed). 

I'm actually hoping to compile the code and output as an AU (Audio Unit) plug-in instead of a VST so I can run it on my iPad under iOS. If anyone would have suggestions on how to achieve that I'd be most grateful ([current issues I'm experiencing are documented in this Reddit thread](https://old.reddit.com/r/cpp_questions/comments/14053p9/anyone_here_have_experience_writing_vst_audio/)).
